### ISSUE TITLE
vdwlamdas template for Frontier branch

### ISSUE THREAD

**Issue by ScottWidmann** [pnnl/PTMPSI#23]
line 385 of gromacs/templates.py (vdwlamdas):

`couple-intramol = vdw-q` throws an error in gromacs v2024.3; it's either "yes" or "no" now.

change to `couple-intramol = yes` ?

**Comment by neffrw** [comment]
I see it was set to `no` in the aqe branch here several days ago: be97c79a4c3451cc03303742e16ce34aae8a5e77 and mentioned in #21

I will update the `lcf` branch with the `aqe` branch's bugfixes once I'm done with the GROMACS auto restart feature. The `lcf` branch contains all the `frontier` branch functionality and we should soon switch to using that from now on. I will need to go through and update all the tutorials on confluence to reference this branch as well as add a new Frontier PTM-Psi module with these new changes.
